### ISSUE TITLE
Release executable?

### ISSUE THREAD

**Issue by VestOfHolding** [shibbo/SMPe#1]
Hi, this project looks really cool! Do you have any plans to release a downloadable executable for this program so one wouldn't have to download the source and compile it?

**Comment by shibbo** [comment]
Considering most of the people in the community no longer want to work with SMP, I will probably not be releasing a stable version.

**Comment by justcamtro** [comment]
> Considering most of the people in the community no longer want to work with SMP, I will probably not be releasing a stable version.

Aw, I was looking forward for it.

**Comment by VestOfHolding** [comment]
Damn. How come people don't want to work with SMP? I'm working on a really fun statistics project with this because of those character die.

I mean, yeah, if it really is just a couple of us then I'll bite the bullet and download Visual Studio and clone the repo, fair enough. Thought it was worth a shot at least. :)

**Comment by shibbo** [comment]
In the end, I already had one on hand of the latest commit. It has been uploaded to the Releases tag.

Thanks.

**Comment by VestOfHolding** [comment]
Sweet! Thanks! Now to continue my hunt for a good SMP bea file, lol.
